name: ui
description: "standardized template for Flutter and Dart Docker projects that is compatible with agile processes"
publish_to: "Application"
version: 0.1.0

environment:
  sdk: ">=3.4.0-212.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  http: ^1.2.1
  mockito: ^5.4.4
  provider: ^6.1.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
   

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  test: ^1.25.2

flutter:
  uses-material-design: true
  assets:
  - assets/favicon.ico
  - assets/favicon.png
  - .env
