# /**
#  * @file docker-compose.yml
#  * @author Azmi ŞAHİN (azmisahin@outlook.com)
#  * @brief running multi-container Docker applications.
#  * @version 0.2.1
#  * @date 2024-01-01
#  *
#  * @copyright Copyright (c) 2024
#  */
version: '3.8'

services:

  application:

    env_file: .env

    build:
      context: ..
      dockerfile: .docker/Dockerfile.$DISTRIB_ID
      target: $APP_ENV
      args:
        - APP_ENV=$APP_ENV
        - APP_NAME=$APP_NAME
        - DISTRIB_ID=$DISTRIB_ID
        - BASE_IMAGE=$BASE_IMAGE
        - WORKSPACE_FOLDER=$WORKSPACE_FOLDER
        - PROJECT_FOLDER=$PROJECT_FOLDER
        - DATA_FOLDER=$DATA_FOLDER
        - HOST_IP=$HOST_IP
        - TCP_PORT=$TCP_PORT
        - TCP_RANGE=$TCP_RANGE
        - SWICH_TRACKING_TRACE=$SWICH_TRACKING_TRACE
        - SWICH_TRACKING_DEBUG=$SWICH_TRACKING_DEBUG
        - SWICH_TRACKING_INFO=$SWICH_TRACKING_INFO
        - SWICH_TRACKING_WARN=$SWICH_TRACKING_WARN
        - SWICH_TRACKING_ERROR=$SWICH_TRACKING_ERROR
        - SWICH_TRACKING_VERBOSE=$SWICH_TRACKING_VERBOSE
        - SWICH_TRACKING_REPORT=$SWICH_TRACKING_REPORT

    volumes:
      - data:/data

    # must be launched in production environments
    command: /bin/sh -c ".docker/command.sh"

    ports:
      # if you need to range
      - "$TCP_RANGE:$TCP_PORT"

    restart: "always"

    # Monitors the health of a container based on criteria you specify.
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://$HOST_IP:$TCP_PORT/" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

    # base limitation
    cpus: $RESOURCE_CPUS
    mem_limit: $RESOURCE_MEMORY

    deploy:
      # for swarm
      replicas: $SCALE
      # base resources
      resources:
        # resources limitation
        reservations:
          devices:
            - driver: nvidia
              count: $RESOURCE_GPUS
              capabilities:
                - gpu
          cpus: $RESOURCE_CPUS
          memory: $RESOURCE_MEMORY
volumes:
  data:
